### PR TITLE
Add a section about browser initiated remote playback

### PR DESCRIPTION
**Pull request by avayvod**

### CODE REVIEW

**Comment by avayvod** [comment]
@mfoltzgoogle @mounirlamouri

**Comment by tidoust** [comment]
The Presentation API uses the expression "from the browser" for a similar feature, so I suggest we do that here as well.

I think it would be useful to relate that feature to the user interface that user agents expose to users for media controls too:
https://html.spec.whatwg.org/multipage/embedded-content.html#expose-a-user-interface-to-the-user

I would expect most implementations will simply add a button there. As with the Presentation API, the feature may be coupled with the selection of the remote device, so we may do not want to restrict the feature to a control in this user interface (one could argue that the notion of user interface is flexible enough to encompass that possibility, though).

In short, I would suggest to replace the first paragraph by:

``` html
<p>
  A user agent MAY support <a data-lt="establish a connection with the remote playback device">
  connecting to a remote playback device</a> from the browser, e.g. by including appropriate
  controls to <a data-lt="expose a user interface to the user">the user interface that is exposed
  to the user</a>. This feature is known as <dfn>browser initiated remote playback</dfn>. A
  <a>user agent</a> that supports <a>browser initiated remote playback</a> SHOULD initiate
  the remote playback only when the user has expressed an intention to do so via a user gesture,
  for example by clicking a button in the browser.
</p>
```

... and to add the following term to the terminology section:

``` html
<a href="https://html.spec.whatwg.org/multipage/embedded-content.html#expose-a-user-interface-to-the-user">expose a user interface to the user</a>
```

I thought the spec already had some prose around these lines. While it's not a change of API surface per se, that seems an important feature to highlight. It provides additional context to understand some aspects of #41 in particular: the transition to remote playback may happen under the hoods without the app doing anything, and potential changes of behavior may "surprise" the app.

In other words, I wonder whether we may include that text in the updated Working Draft that the group is about to publish. @anssiko @avayvod what do you think?

**Comment by mounirlamouri** [comment]
@foolip I can't find something in the HTMLMediaElement specification that specifies that the UA can trigger the algorithms. Do you think the Remote Playback API should specify this?

@avayvod I'm not sure this should be normative text. I would put this as non-normative if not even as a note to say that if the UA triggers remote playback from browser UI, it should fire the events appropriately to allow web pages to react.

**Comment by foolip** [comment]
Are we talking about cases where the UA does the equivalent of calling `video.play()` or `video.remote.promt()` and so on? Without any user interaction I don't think HTML does that, but https://html.spec.whatwg.org/multipage/embedded-content.html#user-interface says a lot of things, including this:

> Where possible (specifically, for starting, stopping, pausing, and unpausing playback, for seeking, for changing the rate of playback, for fast-forwarding or rewinding, for listing, enabling, and disabling text tracks, and for muting or changing the volume of the audio), user interface features exposed by the user agent must be implemented in terms of the DOM API described above, so that, e.g., all the same events fire.

**Comment by anssiko** [comment]
@avayvod would you be fine with @tidoust's proposal? I feel aligning language with the Presentation API would make the spec easier to review for people familiar with the Presentation API.

If so, could you update this PR accordingly and land it, so we could roll this PR into the WD to be published very soon?

**Pull request merged**
