### PR TITLE
Fix #87: Add preliminary implementation report

### LINKED ISSUE #87: Produce a preliminary implementation report
To be able to publish a Candidate Recommendation #73, we need a preliminary implementation report similarly to the [Presentation API test results] (see test results column).

@avayvod @mounirlamouri, are you happy with the current coverage of the [Remote Playback API test suite]? (You added idlharness tests that were initially missing, is [TODO] up to date?)

@Honry could perhaps help you produce a preliminary implementation report using the Chrome for Android implementation https://crbug.com/578833 if you so prefer, and/or help update the test suite if some tests are still missing.

[Presentation API test results]: https://www.w3.org/wiki/Second_Screen/Implementation_Status#Tests
[Remote Playback API test suite]: https://github.com/w3c/web-platform-tests/tree/master/remote-playback
[TODO]: https://github.com/w3c/web-platform-tests/tree/master/remote-playback#todo

### PR DESCRIPTION
**Pull request by anssiko**
I added the usual entry to the [implementation status wiki], linked from the specification.

Fixes #87.

This report should be good enough for a CR, we continue perfect the test automation plan in #92.

PTAL @avayvod @mounirlamouri @Honry

[implementation status wiki]: https://www.w3.org/wiki/Second_Screen/Implementation_Status#Remote_Playback_API

### CODE REVIEW

**Comment by Honry** [comment]
@anssiko, is that appropriate to name me as the test facilitator? As I never contribute tests for this API.

**Comment by anssiko** [comment]
@Honry, the test facilitator does not necessarily need to write tests, see https://www.w3.org/wiki/Second_Screen/Work_Mode#Test_Facilitator

If you would like to see someone else in this role, please suggest some names. That said, I'd be happy to have you in this role.

**Comment by Honry** [comment]
Oh, thanks for the clarification, I'd glad to be the role. :)

**Comment by Honry** [comment]
And for the wiki, LGTM.

**Comment by anssiko** [comment]
@Honry, thanks for the review, and for volunteering to be the test facilitator for the Remote Playback API.

**Pull request merged**
