### PR TITLE
Update SOTD to clarify the status of #41

### PR DESCRIPTION
**Pull request by markafoltz**
If we are ready to close Issue #41, this can be merged to remove the reference in the SOTD.

***
[Preview](https://s3.amazonaws.com/pr-preview/mfoltzgoogle/remote-playback/issue-41-update-sotd.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/remote-playback/8167724...mfoltzgoogle:f16a463.html)

### CODE REVIEW

**Comment by markafoltz** [comment]
PTAL @avayvod @anssiko @tidoust

**Comment by avayvod** [comment]
LGTM, but I guess it does depend on whether we can close the issue #41 or not at this point.
There was no updates for the past 10 days as far as I can see.

**Comment by anssiko** [comment]
I missed this PR while processing my backlog and made an alternative suggestion in https://github.com/w3c/remote-playback/issues/41#issuecomment-321216852

I think it might be worthwhile to keep reference to #41 in the SOTD of the CR. I believe we should be able to go to CR with that particular issue open. I'll let @tidoust to confirm that.

**Comment by markafoltz** [comment]
Thanks for looking @anssiko.  I pushed an updated PR with your suggested wording.

**Comment by anssiko** [comment]
@mounirlamouri, feel free to merge when you're happy with the updated text.

**Comment by mounirlamouri** [comment]
Updated text lgtm. The PR title doesn't seem to fully match the change though.

**Pull request merged**
