### PR TITLE
fix typo in example

### PR DESCRIPTION
**Pull request by troggy**
***
<a href="https://pr-preview.s3.amazonaws.com/troggy/remote-playback/pull/155.html" title="Last updated on Apr 15, 2024, 8:21 AM UTC (7ce6721)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/remote-playback/155/ac9a2bb...troggy:7ce6721.html" title="Last updated on Apr 15, 2024, 8:21 AM UTC (7ce6721)">Diff</a>

### CODE REVIEW

**Comment by troggy** [comment]
insignificant

**Comment by chrisn** [comment]
This looks like a valid correction, worth including in the spec.

**Comment by tidoust** [comment]
I took the liberty to re-open the pull request, which I'll now merge.

I hope the IPR bot that runs on pull requests did not scare you away @troggy. We don't need you to commit to anything to fix typos in particular. We would only start pondering things if the update touched on a normative part of the specification.

**Review by anssiko — COMMENTED** [review]
@troggy thanks for the contribution and attention to detail.

Example code we include in the specs _should_ be correct so we won't frustrate any web developers who try the API out for the first time, starting with the examples. But sometimes bugs get in spec examples too.

Typo fixes in examples are very helpful and well received contributions. We all know how frustrating it is when a piece of code you grab from the spec does not work. It should just work. Please do not hesitate to submit further improvements to the examples, or even propose new examples!

**Pull request merged**
