### PR TITLE
Editorial: simplify spec by using new features in ReSpec

### PR DESCRIPTION
**Pull request by Honry**
- Use `` instead of \<code>\</code>
- Use |variable:Type| instead of \<var>\</var>

Splitted from #133

***
<a href="https://pr-preview.s3.amazonaws.com/Honry/remote-playback/pull/135.html" title="Last updated on Apr 15, 2020, 5:29 AM UTC (ede961a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/remote-playback/135/9e3da8a...Honry:ede961a.html" title="Last updated on Apr 15, 2020, 5:29 AM UTC (ede961a)">Diff</a>

### CODE REVIEW

**Comment by Honry** [comment]
@mounirlamouri, PTAL, thanks!

**Comment by mounirlamouri** [comment]
It seems a bit weird to me to have a mix of markdown style and html style. Is this the recommended way to do things in respec?

**Comment by Honry** [comment]
> Is this the recommended way to do things in respec?

ReSpec is replacing more and more html style with markdown style. I suppose it recommends using markdown style to simplify the spec.

See https://github.com/w3c/respec/wiki/Shorthands-Guide#what-are-shorthands

> Shorthands save you time and work: you write a lot less HTML, and ReSpec does all the linking and error checking for you.

**Comment by markafoltz** [comment]
This looks straightforward to me and I suppose the is the modern way to use ReSpec. 

Unless I hear comments from @mounirlamouri or others in the group with suggested changes, I will merge this in the next couple of weeks.

**Review by mounirlamouri — APPROVED** [review]
LGTM! I'm afraid, it's fell through the cracks.

**Pull request merged**
