### PR TITLE
Editorial: use modern features of ReSpec

### PR DESCRIPTION
**Pull request by Honry**
- Clean up Dependensies section
- Use morden ReSpec features
- Use ES6 in examples
- A few other minor changes

***
<a href="https://pr-preview.s3.amazonaws.com/Honry/remote-playback/pull/133.html" title="Last updated on Mar 2, 2020, 6:31 AM UTC (53254cd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/remote-playback/133/2fe00fb...Honry:53254cd.html" title="Last updated on Mar 2, 2020, 6:31 AM UTC (53254cd)">Diff</a>

### CODE REVIEW

**Comment by Honry** [comment]
Happen to see the spec is still using the very old ReSpec features when I start editor work for the test automation API, so I make some improvement on the way.
@anssiko, @mounirlamouri, PTAL, thanks!

**Comment by anssiko** [comment]
@Honry thanks! I'll defer to the editor @mounirlamouri.

**Comment by mounirlamouri** [comment]
Thank you for the PR @Honry. I was wondering if you could split this into a few different changes. Ideally, you would have one pull request for each of the changes (dependencies, respec, es6, others) so I can evaluate them independently.

At a first glance, I'm not sure some changes (eg. `<a>foo</a>` to `{{foo}}` or `<code>bar</code>` to `'bar'`) are really needed but some of them seem good to have.

**Comment by Honry** [comment]
@mounirlamouri, no problem, I'll split the PR right now and sorry for the inconvenience.

**Pull request closed without merging**
